version: "2"

services:
    pubsub:
        image: archmixoss/gcloud-pubsub
        volumes:
            - ./data:/opt/data
        environment:
            - PUBSUB_PROJECT_ID=archmix
            - PUBSUB_LISTEN_PORT=8432
        ports:
            - "8432:8432"